const { test } = require('node:test')
const assert = require('node:assert/strict')
const { createChallenge } = require('../electron/challenge.cjs')
const { mockGame } = require('../electron/collector.cjs')
const game = (kills, time) => { const d = mockGame(0); d.allPlayers[0].scores.kills = kills; d.gameData.gameTime = time; return d }
test('点赞数量阈值保留余额，重复消息与重复关注不加目标', () => {
  const c = createChallenge(); c.action('start')
  c.event({ id:'1',type:'like',count:250 }); c.event({ id:'1',type:'like',count:250 })
  assert.equal(c.state.target,12); assert.equal(c.state.likeBalance,50)
  c.event({id:'2',type:'like',count:50}); assert.equal(c.state.target,13)
  c.event({id:'3',type:'follow',userId:'a'}); c.event({id:'4',type:'follow',userId:'a'})
  assert.equal(c.state.target,14); assert.equal(c.state.stats.follows,1)
})
test('接入基线、临时补记追平、永久修正、跨局累计', () => {
  const c = createChallenge(); c.action('start'); c.game(game(5,100),1000)
  assert.equal(c.snapshot().completed,0)
  c.action('pending',undefined,1100); c.game(game(6,101),1200); assert.equal(c.snapshot().completed,1); assert.equal(c.state.pending,0)
  c.game(game(6,102),1400); assert.equal(c.snapshot().completed,1)
  c.action('completed',8); c.game(game(7,103),1600); assert.equal(c.snapshot().completed,9)
  c.game(game(0,5),1800); c.game(game(1,10),2000); assert.equal(c.snapshot().completed,10)
})
test('暂停不累计，恢复建立新基线，长断线要求核对', () => {
  const c = createChallenge(); c.action('start'); c.game(game(0,1),1000); c.action('pause')
  c.game(game(2,10),2000); c.event({id:'1',type:'like',count:100})
  c.action('start'); c.event({id:'1',type:'like',count:100}); c.game(game(3,12),3000)
  assert.equal(c.state.target,10); assert.equal(c.snapshot().completed,0)
  c.game(game(4,13),3200); assert.equal(c.snapshot().completed,1)
  c.game(game(9,200),130001); assert.equal(c.state.status,'paused'); assert.equal(c.snapshot().completed,1)
})
test('评论只展示不奖励，持久化恢复保留计数并暂停', () => {
  const c = createChallenge(); c.action('start')
  c.event({id:'1',type:'comment',text:'加油',userId:'a'},1000)
  c.event({id:'2',type:'comment',text:'加油',userId:'a'},2000)
  assert.equal(c.state.target,10); assert.equal(c.state.stats.comments,2)
  const restored = createChallenge(JSON.parse(JSON.stringify(c.state)))
  assert.equal(restored.state.status,'paused'); restored.action('start')
  restored.event({id:'1',type:'comment',text:'加油',userId:'a'},100000)
  assert.equal(restored.state.target,10); assert.equal(restored.state.stats.comments,2)
})
test('标准化礼物增量按消息 ID 去重，暂停消息恢复后不补算', () => {
  const c=createChallenge()
  c.action('rules',{likesEnabled:true,likeEvery:100,followEnabled:true,follow:1,gifts:[{platformId:'douyin',giftId:'g',name:'小心心',icon:null,reward:1}]})
  c.action('start')
  const e={type:'gift',platformId:'douyin',giftId:'g',userId:'user'}
  c.event({...e,id:'1',count:1});c.event({...e,id:'2',count:2});c.event({...e,id:'2',count:2})
  assert.equal(c.state.target,13);assert.equal(c.state.stats.gifts,3)
  c.action('pause');c.event({...e,id:'3',count:3});c.action('start');c.event({...e,id:'3',count:3});c.event({...e,id:'4',count:1})
  assert.equal(c.state.target,14);assert.equal(c.state.stats.gifts,4)
})
