const loadRenderer=require('./load-renderer.cjs')
const {test}=require('node:test'),assert=require('node:assert/strict')
const model=()=>Promise.resolve(loadRenderer('../src/display-feed.ts'))
const rows=(a,b,type='comment')=>Array.from({length:b-a+1},(_,i)=>({rowId:a+i,type,text:String(a+i)}))
const packet=(messages,extra={})=>({generation:'g',messages,retainedIds:messages.map(r=>r.rowId),limit:1000,perTypeLimit:200,...extra})
const tick=()=>new Promise(r=>setImmediate(r))
test('authoritative sparse retention removes evicted rows including empty deltas',async()=>{
 const {mergeDisplayFeed}=await model()
 const previous={generation:'g',messages:[{rowId:1,type:'gift'},{rowId:2,type:'enter'}]}
 const next=mergeDisplayFeed(previous,packet([{rowId:8,type:'enter'}],{retainedIds:[1,8],reset:false}))
 assert.deepEqual(next.messages.map(r=>r.rowId),[1,8])
 const empty=mergeDisplayFeed(next,packet([],{retainedIds:[1],after:9,total:9}))
 assert.deepEqual(empty.messages.map(r=>r.rowId),[1]);assert.equal(empty.after,9)
})
test('bounded merge deduplicates overlaps, respects category ceilings and resets generation',async()=>{
 const {mergeDisplayFeed,restoreAnchor,captureAnchor}=await model()
 const first=mergeDisplayFeed(null,packet(rows(1,200)))
 const anchor=captureAnchor(first.messages,119*64+7)
 const next=mergeDisplayFeed(first,packet(rows(200,220),{retainedIds:rows(21,220).map(r=>r.rowId)}))
 assert.equal(next.messages.length,200);assert.equal(next.messages[0].rowId,21)
 assert.deepEqual(restoreAnchor(next.messages,anchor,320),{scrollTop:99*64+7,expired:false})
 const reset=mergeDisplayFeed(next,packet(rows(1,2),{generation:'b'}))
 assert.deepEqual(reset.messages.map(m=>m.rowId),[1,2])
 assert.deepEqual(restoreAnchor(next.messages,{rowId:1,offset:0},320),{scrollTop:0,expired:true})
 const over=mergeDisplayFeed(null,packet([...rows(1,300),...rows(301,600,'gift')]))
 assert.equal(over.messages.length,400);assert.equal(over.messages.filter(r=>r.type==='gift').length,200)
})
test('metadata validation rejects oversized sets and incompatible old backends safely',async()=>{
 const {mergeDisplayFeed}=await model()
 assert.throws(()=>mergeDisplayFeed(null,packet([],{retainedIds:Array(1001).fill(1)})),/metadata|元数据/)
 assert.throws(()=>mergeDisplayFeed(null,packet([],{perTypeLimit:201})),/metadata|元数据/)
 const old=mergeDisplayFeed({messages:[{rowId:1,type:'gift'}]},{generation:'old',messages:rows(1,2)})
 assert.deepEqual(old.messages,[]);assert.match(old.error,/重启/);assert.equal(old.compatibility,true)
})
test('filter/search distinguishes zero matches from zero retained records and clamps virtualization',async()=>{
 const {displayRange,filterMessages,messageEmptyState,messageSummary}=await model()
 const feed=packet([{rowId:1,type:'gift',giftName:'rose'}],{counts:{gift:128},retainedCounts:{gift:1}})
 const filtered=filterMessages(feed.messages,['gift'],'gift','absent')
 assert.equal(filtered.length,0)
 assert.match(messageEmptyState(feed,'gift','absent').title,/没有匹配/)
 assert.match(messageSummary(feed,'gift'),/累计收到 128 个礼物.*当前保留 1 条礼物消息/)
 assert.match(messageEmptyState({...feed,retainedCounts:{gift:0}},'gift').title,/已不在/)
 assert.match(messageEmptyState({...feed,cleared:true},'gift').title,/已清屏/)
 assert.match(messageEmptyState(packet([]),'follow').title,/尚未收到/)
 assert.deepEqual(displayRange(1,30000,320),{scrollTop:0,start:0,end:1})
})
test('disabled-only retained messages are distinct from no received messages in enabled categories',async()=>{
 const {messageEmptyState,messageSummary,filterMessages}=await model()
 const feed=packet(rows(1,1),{total:1,counts:{comment:1,gift:0},retainedCounts:{comment:1,gift:0}})
 assert.equal(filterMessages(feed.messages,['gift']).length,0)
 assert.match(messageEmptyState(feed,'all','',['gift']).title,/未启用分类/)
 assert.match(messageSummary(feed,'all',['gift']),/全分类累计收到 1 条消息.*当前启用分类保留 0 条/)
 assert.match(messageEmptyState(packet([],{counts:{},total:0}),'all','',['gift']).title,/尚未收到/)
})
test('enabled-category eviction remains visible when disabled categories retain rows',async()=>{
 const {messageEmptyState,messageSummary}=await model()
 const feed=packet(rows(2,2),{total:2,counts:{comment:1,gift:128},retainedCounts:{comment:1,gift:0}})
 assert.match(messageEmptyState(feed,'all','',['gift']).title,/已启用分类消息已不在保留范围/)
 assert.doesNotMatch(messageEmptyState(feed,'all','',['gift']).title,/尚未收到/)
 assert.match(messageSummary(feed,'all',['gift']),/当前启用分类保留 0 条/)
})
test('disabling selected gift permanently returns to all when re-enabled',async()=>{
 const {displayFilterReducer}=await model()
 assert.equal(displayFilterReducer('gift',{available:['comment']}),'all')
 assert.equal(displayFilterReducer('all',{available:['comment','gift']}),'all')
})
test('native visibility events win delayed initial getter and subscriptions dispose cleanly',async()=>{
 const {subscribeFeedVisibility}=await model();let resolve,notify,listener,removed=0;const changes=[]
 const doc={visibilityState:'visible',addEventListener:(name,cb)=>{listener=cb},removeEventListener:(name,cb)=>{assert.equal(cb,listener);removed++}}
 const api={getMainVisibility:()=>new Promise(r=>resolve=r),onMainVisibility:cb=>{notify=cb;return()=>removed++}}
 const off=subscribeFeedVisibility({api,document:doc,nativeVisibility:true,active:true,onChange:v=>changes.push(v)})
 assert.equal(changes.at(-1),false)
 notify(false);resolve(true);await tick();assert.equal(changes.at(-1),false)
 notify(true);assert.equal(changes.at(-1),true)
 doc.visibilityState='hidden';listener();assert.equal(changes.at(-1),false)
 off();const n=changes.length;notify(true);assert.equal(changes.length,n);assert.equal(removed,2)
 let lateResolve;const late=[]
 const cleanup=subscribeFeedVisibility({api:{...api,getMainVisibility:()=>new Promise(r=>lateResolve=r)},document:doc,nativeVisibility:true,active:true,onChange:v=>late.push(v)})
 cleanup();const before=late.length;lateResolve(true);await tick();assert.equal(late.length,before)
})
test('controller coalesces requests, rejects stale scope, suspends hidden work and disposes',async()=>{
 const {createDisplayFeedController}=await model();const calls=[],states=[]
 const controller=createDisplayFeedController({request:(cursor,scope)=>new Promise((resolve,reject)=>calls.push({cursor,scope,resolve,reject})),onChange:s=>states.push(s)})
 controller.setScope(1);controller.markDirty('a');controller.markDirty('b');assert.equal(calls.length,1)
 calls[0].resolve(packet(rows(1,2),{contextVersion:1,after:2}));await tick()
 assert.equal(calls.length,2);assert.equal(states.at(-1).messages.length,2)
 controller.setScope(2);assert.equal(states.at(-1).messages.length,0);assert.equal(calls.length,2)
 calls[1].resolve(packet(rows(3,4),{contextVersion:1,after:4}));await tick()
 assert.equal(calls.length,3);assert.equal(calls[2].scope,2)
 controller.setActive(false);calls[2].resolve(packet(rows(8,9),{contextVersion:2,after:9}));await tick()
 assert.equal(states.at(-1).messages.length,0)
 controller.markDirty('c');assert.equal(calls.length,3);controller.setActive(true);assert.equal(calls.length,4)
 calls[3].resolve(packet(rows(8,9),{contextVersion:2,after:9}));await tick()
 controller.retry();assert.equal(states.at(-1).messages.length,2)
 calls[4].reject(Error('temporary'));await tick();assert.match(states.at(-1).error,/temporary/)
 controller.retry();const count=states.length;controller.dispose();calls[5].resolve(packet(rows(10,11),{contextVersion:2}));await tick()
 controller.retry();controller.setScope(3);assert.equal(states.length,count);assert.equal(calls.length,6)
})
