const {test}=require('node:test')
const assert=require('node:assert/strict')
const {createDiagnostics}=require('../electron/douyin-diagnostics.cjs')

test('diagnostics retain only 50 newest safe metadata entries',()=>{
  const diagnostics=createDiagnostics()
  for(let i=0;i<51;i++)diagnostics.record({method:'WebcastChatMessage',stage:'decode',error:Object.assign(Error('cookie=secret https://private.example/'),{code:'ERR_INVALID_ARG_TYPE'}),payloadSize:i})
  const entries=diagnostics.snapshot()
  assert.equal(entries.length,50)
  assert.equal(entries[0].payloadSize,1)
  assert.equal(entries.at(-1).payloadSize,50)
  assert.deepEqual(Object.keys(entries[0]).sort(),['code','method','payloadSize','stage','timestamp'])
  assert.equal(entries[0].code,'ERR_INVALID_ARG_TYPE')
  assert.equal(typeof entries[0].timestamp,'number')
  assert.ok(!JSON.stringify(entries).includes('secret'))
  diagnostics.clear()
  assert.deepEqual(diagnostics.snapshot(),[])
})

test('diagnostics reject unsafe method, stage, code and payload size',()=>{
  const diagnostics=createDiagnostics()
  diagnostics.record({method:'WebcastChatMessage?cookie=secret',stage:'processing?url=private',error:Object.assign(Error('user=private'),{code:'TOKEN_SECRET'}),payloadSize:Infinity})
  assert.deepEqual(diagnostics.snapshot().map(({timestamp,...entry})=>entry),[{method:'unknown',stage:'unknown',code:'UNKNOWN',payloadSize:0}])
  assert.ok(!JSON.stringify(diagnostics.snapshot()).includes('secret'))
})

test('unsupported method counts are bounded, sanitized, and clearable without storing payloads',()=>{
  const d=createDiagnostics()
  d.recordUnsupported?.('WebcastRanklistMessage')
  d.recordUnsupported?.('WebcastRanklistMessage')
  d.recordUnsupported?.('WebcastMessage?cookie=secret')
  const summary=d.unsupported?.()
  assert.deepEqual(summary?.items,[{method:'WebcastRanklistMessage',count:2},{method:'unknown',count:1}])
  for(let i=0;i<60;i++)d.recordUnsupported('WebcastExtra'+i+'Message')
  const bounded=d.unsupported()
  assert.equal(bounded.items.length,50)
  assert.equal(bounded.total,63)
  assert.equal(bounded.otherCount,12)
  assert.ok(!JSON.stringify(bounded).includes('secret'))
  d.clear();assert.deepEqual(d.unsupported(),{items:[],otherCount:0,total:0,limit:50})
})
