const assert=require('node:assert/strict')
const wire=require('../electron/douyin-wire.cjs')
module.exports=async({main,product,run,wait,until,click,capture,checkLayout})=>{
  const fixture=require('./fixtures/smoke-platform.cjs'),target=product.snapshot().target
  await click('[data-testid="tab-messages"]')
  await click('[data-testid="messages-more"] summary')
  await click('[data-testid="open-extensions"]')
  await until('document.querySelector(".extension-empty")')
  await click('[data-testid="extension-sampling"]')
  assert.equal((await product.query('extensions')).sampling,true)
  const user=wire.encode([[1,9007199254740993n],[3,'小橘同学']])
  fixture.emitExtension('WebcastEmojiChatMessage',[[2,user],[3,123],[5,'加油🍊']])
  for(let i=0;i<100;i++)fixture.emitExtension('WebcastRoomStatsMessage',[[2,'123万热度'],[9,1234567]])
  fixture.emitExtension('WebcastLuckyBoxRewardMessage',[[2,'cookie=secret-fixture']])
  fixture.emitExtension('WebcastRoomMessage',[[2,'测试长文案'.repeat(80)]])
  await until('document.querySelectorAll(".extension-row").length===4')
  await click('.extension-row summary')
  await until('document.querySelector(".extension-detail")?.textContent.includes("9007199254740993")')
  await run('window.extensionNode=document.querySelector(".extension-row")')
  fixture.emitExtension('WebcastEmojiChatMessage',[[2,user],[5,'继续加油']])
  await until('document.querySelector(".extension-row").textContent.includes("继续加油")')
  assert.equal(await run('window.extensionNode===document.querySelector(".extension-row")&&window.extensionNode.open'),true)
  assert.equal(product.snapshot().target,target)
  assert.equal((await product.query('extensions')).items.find(i=>i.method==='WebcastRoomStatsMessage').count,100)
  assert.equal((await product.query('extensions')).samples.length,6)
  const hidden=wire.encode([[1,987654321],[3,'不应显示的匿名昵称']])
  fixture.emitExtension('WebcastRoomRankMessage',[[2,wire.encode([[1,user],[2,'1.2万'],[3,0]])],[2,wire.encode([[1,hidden],[2,'999'],[3,1]])]])
  fixture.emitExtension('WebcastHotChatMessage',[[2,'热门话题'],[3,'加油'],[4,10000],[8,'精彩']])
  fixture.emitExtension('WebcastRoomIndicatorMessage',[[1,Buffer.from([255])]])
  fixture.emitExtension('WebcastHotRoomMessage',[[2,wire.encode([[1,'9007199254740993']])]])
  fixture.emitExtension('WebcastLotteryEventNewMessage',[[1,Buffer.from([255])],[2,'secret-fixture']])
  for(const type of ['InRoomBannerRefresh','RoomCommentTopic','PrivilegeScreenChat'])fixture.emitExtension(`Webcast${type}Message`,[[1,Buffer.from([255])],[2,'secret-fixture']])
  fixture.emitExtension('WebcastAudioChatMessage',[[2,user],[3,'语音文字：加油'],[4,'https://private.invalid/secret-fixture'],[5,'30']])
  fixture.emitExtension('WebcastLotteryDrawResultEventMessage',[[1,Buffer.from([255])],[2,'secret-fixture']])
  fixture.emitExtension('WebcastDataLifeLiveMessage',[[1,Buffer.from([255])],[2,'secret-fixture']])
  fixture.emitExtension('WebcastRoomStreamAdaptationMessage',[[2,1]])
  await until('document.querySelectorAll(".extension-row").length===16')
  await until('document.querySelector(".extension-content").textContent.includes("最多 29 种")')
  assert.equal(product.snapshot().target,target)
  assert.equal(await run('document.querySelector(".extension-list").textContent.includes("不应显示的匿名昵称")'),false)
  await click('.extension-row:nth-child(5) summary')
  await click('.extension-row:nth-child(6) summary')
  await click('.extension-row:nth-child(7) summary')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(5)").textContent.includes("匿名用户")'),true)
  assert.equal(await run('document.querySelector(".extension-row:nth-child(6) .extension-level").textContent'),'部分解析')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(7) .extension-level").textContent'),'待确认')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(8) .extension-level").textContent'),'部分解析')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(9) .extension-level").textContent'),'待确认')
  await run('document.querySelector(".extension-row:nth-child(6)").scrollIntoView({block:"start"})')
  await capture('26-new-extension-types.png')
  for(const index of [10,11,12])assert.equal(await run(`document.querySelector('.extension-row:nth-child(${index}) .extension-level').textContent`),'待确认')
  await click('.extension-row:nth-child(13) summary')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(13) .extension-level").textContent'),'部分解析')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(13)").textContent.includes("语音文字：加油")'),true)
  assert.equal(await run('document.querySelector(".extension-list").textContent.includes("secret-fixture")'),false)
  await run('document.querySelector(".extension-row:nth-child(11)").scrollIntoView({block:"start"})');await capture('28-audio-and-pending-types.png')
  await click('.extension-row:nth-child(14) summary')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(14) .extension-level").textContent'),'待确认')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(14)").textContent.includes("不视为收到礼物")'),true)
  await run('document.querySelector(".extension-row:nth-child(14)").scrollIntoView({block:"start"})');await capture('29-lottery-result.png')
  await click('.extension-row:nth-child(16) summary')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(15) .extension-level").textContent'),'待确认')
  assert.equal(await run('document.querySelector(".extension-row:nth-child(16) .extension-level").classList.contains("parsed")'),true)
  assert.equal(await run('document.querySelector(".extension-row:nth-child(16)").textContent.includes("适配类型（原值）")'),true)
  await run('document.querySelector(".extension-row:nth-child(16)").scrollIntoView({block:"start"})');await capture('30-stream-adaptation.png')
  await run('document.querySelector(".modal").scrollTop=0')
  await checkLayout();await capture('23-extensions-small.png')
  main.setSize(1360,920);await wait(180);await capture('24-extensions.png');await checkLayout()
  await click('.extension-samples summary')
  assert.equal(await run('document.querySelector(".extension-samples").textContent.includes("secret-fixture")'),false)
  await click('[aria-label="关闭弹窗"]')
  await click('[aria-label="打开设置"]');await run('[...document.querySelectorAll(".settings-tabs button")].find(b=>b.textContent==="高级诊断").click()');await click('.advanced-options summary')
  await click('.extension-inline summary');await until('!!document.querySelector(".extension-sample-status")')
  await click('[data-testid="extension-sampling"]')
  assert.equal((await product.query('extensions')).sampling,false)
  await product.action('logout')
  await until('!document.querySelector(".extension-content")')
  assert.equal((await product.query('extensions')).items.length,0)
}
