const {test}=require('node:test'),assert=require('node:assert/strict')
const {createNormalizer,scopeKey}=require('../electron/interaction-normalizer.cjs')
const {createGiftCatalog}=require('../electron/gift-catalog.cjs')
const {createFeed}=require('../electron/message-feed.cjs')
const scope={platformId:'douyin',accountScope:'alice',roomId:'room'}
test('legacy replay and combo keys migrate without re-award; suppressed delivery still advances high water',()=>{
 const prefix=scopeKey(scope),group=JSON.stringify([prefix,'u','gift','combo']),id=JSON.stringify([prefix,'combo','u','gift','combo',7])
 const n=createNormalizer({seen:[id],combos:[[group,3]]})
 assert.equal(n.normalize({id:'message',type:'gift',combo:true,userId:'u',giftId:'gift',groupId:'combo',count:7},scope),null)
 const saved=n.export();assert.equal(saved.combos[0][1],7);assert.equal(saved.seen[0].length,43)
 const r=createNormalizer(saved)
 assert.equal(r.normalize({id:'next',type:'gift',combo:true,userId:'u',giftId:'gift',groupId:'combo',count:8},scope).count,1)
})
test('feed stale cursor and clear return bounded reset windows with new generation',()=>{
 const f=createFeed(3);for(let i=0;i<5;i++)f.ingest({id:String(i),type:'comment'})
 const first=f.query();assert.equal(first.messages.length,3)
 assert.equal(f.query({generation:first.generation,after:0}).reset,true)
 assert.deepEqual(f.query({generation:first.generation,after:5}).messages,[])
 f.clear();const next=f.query({generation:first.generation,after:5});assert.equal(next.reset,true);assert.equal(next.messages.length,0)
})
test('canonical catalog exports omit merged duplicates and evict least recently used scopes within 16 MiB',()=>{
 const c=createGiftCatalog(),icon='https://example.test/'+ 'a'.repeat(1000000)
 for(let i=0;i<18;i++)c.replace({...scope,roomId:String(i)},[{giftId:'g',name:'gift',icon}])
 const saved=c.export();assert.ok(Buffer.byteLength(JSON.stringify(saved))<=16*1024*1024)
 assert.equal(saved.some(([key])=>key===scopeKey({...scope,roomId:'0'})),false)
 assert.equal(saved.some(([key])=>key===scopeKey({...scope,roomId:'17'})),true)
 assert.ok(saved.every(([,value])=>value.items===undefined))
 assert.equal(createGiftCatalog(saved).snapshot({...scope,roomId:'17'}).items.length,1)
})
