const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
module.exports=async({main,product,run,wait,until,click,input,capture,openOverlay,getOverlay,output})=>{
 const errors=[]
 const watch=()=>getOverlay().webContents.on('console-message',details=>{if(details.level==='error')errors.push(details.message)})
 const screen=code=>getOverlay().webContents.executeJavaScript(code)
 const screenUntil=async code=>{for(let i=0;i<70;i++){if(await screen(code))return;await wait(50)}throw Error('Display assertion timed out: '+code)}
 const screenshot=async name=>{getOverlay().showInactive();await screen('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');await wait(150);fs.writeFileSync(path.join(output,name),(await getOverlay().webContents.capturePage()).toPNG())}
 const fits='(()=>{const e=document.querySelector(".broadcast-screen"),lower=document.querySelector(".broadcast-lower");return e&&e.scrollWidth<=innerWidth&&e.scrollHeight<=innerHeight&&[...document.querySelectorAll(".broadcast-score strong")].length===2&&[...document.querySelectorAll(".broadcast-score strong")].every(n=>n.scrollWidth<=n.clientWidth+1&&n.getBoundingClientRect().width<=n.parentElement.clientWidth+1)&&[...document.querySelectorAll(".broadcast-rule")].every(n=>n.clientHeight>=18&&n.getBoundingClientRect().bottom<=lower.getBoundingClientRect().bottom)})()'
 await product.action('rules',{...product.display().rules,followEnabled:false,commentsEnabled:false})
 await click('[data-testid="challenge-display-settings"]')
 await input('[data-testid="overlay-title-input"]','今晚一起冲！')
 await run('window.__overlayTitle=document.querySelector("[data-testid=overlay-title-input]");window.__overlayTitle.focus()')
 await product.action('target',23);await wait(350)
 assert.equal(await run('window.__overlayTitle===document.activeElement&&window.__overlayTitle.value==="今晚一起冲！"'),true,'Live updates retain unsaved title and focused input')
 await click('[data-testid="overlay-save"]');assert.equal(product.display().overlaySettings.title,'今晚一起冲！')
 await click('[aria-label="关闭弹窗"]');await click('[data-testid="challenge-display-open"]');watch();await click('[data-testid="challenge-display-settings"]')
 await screenUntil('document.querySelector("[data-testid=overlay-target]")?.textContent==="23"')
 await screenUntil('document.querySelector(".broadcast-rule img")?.naturalWidth>0')
 assert.equal(await screen('document.querySelectorAll(".display-toolbar button").length'),3,'Capture window exposes only own-window settings, close and lock controls')
 assert.equal(await screen('document.querySelectorAll("button:not(.display-toolbar button):not(.overlay-operations button),input,select").length'),0)
 assert.deepEqual(getOverlay().getContentSize(),[320,380])
 await input('[data-testid="overlay-transparency"]','55')
 await until('getComputedStyle(document.querySelector(".is-embedded .broadcast-backdrop")).opacity==="0.45"')
 assert.equal(product.display().overlaySettings.backgroundTransparency,25,'Slider preview does not persist every movement')
 await click('[data-testid="overlay-save"]')
 assert.equal(product.display().overlaySettings.backgroundTransparency,55)
 await screenUntil('getComputedStyle(document.querySelector(".broadcast-backdrop")).opacity==="0.45"')
 await input('[data-testid="overlay-transparency"]','25');await click('[data-testid="overlay-save"]')
 assert.equal(getOverlay().hasShadow(),false)
 assert.equal(await screen('getComputedStyle(document.querySelector(".broadcast-screen")).borderRadius'),'4px')
 assert.equal(await screen('getComputedStyle(document.querySelector(".broadcast-screen")).borderWidth'),'0px')
 assert.equal(await screen('document.querySelector(".broadcast-score").getBoundingClientRect().bottom<document.querySelector(".broadcast-rules").getBoundingClientRect().top'),true)
 for(const value of [0,25,100]){
  await product.action('overlaySettings',{...product.display().overlaySettings,backgroundTransparency:value})
  await screenUntil('getComputedStyle(document.querySelector(".broadcast-backdrop")).opacity==="'+((100-value)/100)+'"')
  getOverlay().showInactive();await wait(250)
  const image=await getOverlay().webContents.capturePage(),size=image.getSize(),bitmap=image.toBitmap()
  const alpha=(x,y)=>bitmap[(y*size.width+x)*4+3]
  assert.ok(Math.abs(alpha(5,180)-Math.round(255*(100-value)/100))<=1,'Native backdrop pixel alpha at '+value)
  assert.equal(alpha(0,0),0,'Rounded corner stays transparent')
  let opaqueText=false
  for(let y=112;y<160;y++)for(let x=16;x<120;x++)if(alpha(x,y)===255)opaqueText=true
  assert.ok(opaqueText,'Score glyphs stay opaque at '+value)
  assert.equal(await screen('getComputedStyle(document.querySelector(".broadcast-content")).opacity'),'1')
  await screenshot('overlay-transparency-'+value+'.png')
 }
 await product.action('overlaySettings',{...product.display().overlaySettings,backgroundTransparency:25})
 const originalRules=product.display().rules
 for(const count of [0,1,4,5,12,30]){
  await product.action('rules',{...originalRules,likesEnabled:false,followEnabled:false,commentsEnabled:false,gifts:Array.from({length:count},(_,i)=>({platformId:'douyin',giftId:'paging-'+i,name:'礼物 '+(i+1),icon:'https://avatar.example.invalid/account.png',reward:1}))})
  await screenUntil('document.querySelectorAll(".broadcast-rule").length==='+Math.min(count,2))
  if(count>2)await screenUntil('document.querySelector(".broadcast-rules-heading").textContent.includes("1 / '+Math.ceil(count/2)+'")')
  assert.equal(await screen(fits),true,'Rule count fits: '+count)
  if(count===30){await wait(8200);assert.equal(await screen('document.querySelector(".broadcast-rules-heading").textContent.includes("2 / 15")&&document.querySelector(".broadcast-rule").textContent.includes("礼物 3")'),true,'Later gift rules are rendered after pagination')}
 }
 await product.action('rules',originalRules)
 await screenUntil('document.querySelectorAll(".broadcast-rule").length===2')
 const ruleNodes=await screen('document.querySelectorAll(".broadcast-rule").length');assert.equal(ruleNodes,2)
 require('./fixtures/smoke-platform.cjs').emit({id:'overlay-gift',type:'gift',giftId:'fixture-heart',giftName:'测试礼物',count:3,userId:'overlay-user',userName:'小橘'})
 await screenUntil('document.querySelector("[data-testid=overlay-target]")?.textContent==='+JSON.stringify(String(product.display().target)))
 const gameBefore=product.snapshot().game,data=require('../electron/collector.cjs').mockGame(0)
 data.allPlayers[0].scores.kills=gameBefore.value+1;data.gameData.gameTime=gameBefore.time+1;product.game(data,'live')
 assert.equal(await screen('!!document.querySelector(".broadcast-reasons,[role=progressbar]")'),false)
 await capture('overlay-settings.png')
 for(const theme of ['cream','arcade','forest','champion']){
  await click(`[data-testid="theme-${theme}"]`);await click('[data-testid="overlay-save"]')
  await screenUntil(`document.querySelector(".broadcast-screen")?.dataset.theme===${JSON.stringify(theme)}`)
  await screenUntil('document.querySelector(".broadcast-rule img")?.naturalWidth>0')
  await screenshot(`overlay-${theme}.png`)
  if(!await screen(fits))console.log('Overlay layout diagnostics',await screen('({viewport:[innerWidth,innerHeight],elements:[...document.querySelectorAll(".broadcast-screen,.broadcast-content,.broadcast-score strong,.broadcast-rule")].map(e=>({class:e.className,size:[e.clientWidth,e.clientHeight],scroll:[e.scrollWidth,e.scrollHeight],rect:e.getBoundingClientRect().toJSON()}))})'))
  assert.equal(await screen(fits),true,'Theme layout fits: '+theme)
 }
 await product.action('target',23);await product.action('completed',5)
 const upperBefore=await screen('document.querySelector(".broadcast-score").getBoundingClientRect().toJSON()')
 const before=product.snapshot();await click('[data-testid="overlay-preview"]');await until('!!document.querySelector(".is-embedded [data-testid=overlay-celebration]")')
 assert.equal(await screen('!!document.querySelector("[data-testid=overlay-celebration]")'),false,'Owner preview stays local to its editor')
 await screen('document.querySelector("[data-testid=display-settings]").click()');await screenUntil('!!document.querySelector("[data-testid=overlay-preview]")');await screen('document.querySelector("[data-testid=overlay-preview]").click()')
 console.log('Overlay smoke: themes verified; preview requested')
 await screenUntil('!!document.querySelector("[data-testid=overlay-celebration]")');await screenshot('overlay-celebration-preview.png')
 assert.deepEqual(await screen('document.querySelector(".broadcast-score").getBoundingClientRect().toJSON()'),upperBefore)
 assert.equal(await screen('document.querySelector(".broadcast-celebration").getBoundingClientRect().top>=document.querySelector(".broadcast-score").getBoundingClientRect().bottom'),true,'Celebration stays beneath counts')
 assert.equal(await screen('document.querySelectorAll(".broadcast-rule").length'),0,'Celebration replaces rules')
 assert.equal(product.snapshot().completed,before.completed);assert.equal(product.snapshot().celebratedAt,before.celebratedAt);assert.deepEqual(product.snapshot().history,before.history)
 // Pure mode recreates the native window; an already emitted preview is only a baseline.
 await screen('document.querySelector("[data-testid=config-close]").click()')
 const old=getOverlay();await click('[data-testid="overlay-pure"]');await click('[data-testid="overlay-save"]')
 console.log('Overlay smoke: pure save sent',!!getOverlay(),getOverlay()===old)
 for(let i=0;i<60&&getOverlay()===old;i++)await wait(50)
 assert.notEqual(getOverlay(),old);watch();console.log('Overlay smoke: new window ready',getOverlay().webContents.isLoading());await screenUntil('!!document.querySelector(".broadcast-screen")')
 assert.equal(await screen('!!document.querySelector("[data-testid=overlay-celebration]")'),false)
 assert.equal(getOverlay().isAlwaysOnTop(),true)
 await click('[aria-label="关闭弹窗"]')
 console.log('Overlay smoke: pure window verified; completing challenge')
 await product.action('completed',23)
 await screenUntil('!!document.querySelector("[data-testid=overlay-celebration]")');await screenshot('overlay-first-achievement.png')
 console.log('Overlay smoke: first achievement verified')
 const at=product.snapshot().celebratedAt;assert.ok(at>0);assert.equal(product.snapshot().status,'running')
 await product.action('target',24);await screenUntil('!document.querySelector("[data-testid=overlay-celebration]")')
 await product.action('completed',22);await product.action('completed',24);await wait(500)
 assert.equal(product.snapshot().celebratedAt,at)
 assert.equal(await screen('!!document.querySelector("[data-testid=overlay-celebration]")'),false,'Corrections and target recross must not replay')
 await product.action('pause');await screenUntil('document.querySelector(".broadcast-challenge-state").textContent.includes("已暂停")')
 console.log('Overlay smoke: no replay verified; closing and reopening')
 const closing=getOverlay();await product.action('overlayClose')
 for(let i=0;i<80&&!closing.isDestroyed();i++)await wait(50)
 assert.equal(closing.isDestroyed(),true,'Reopen waits for the guarded native close to complete')
 await openOverlay();watch();await screenUntil('!!document.querySelector(".broadcast-screen")')
 assert.equal(await screen('!!document.querySelector("[data-testid=overlay-celebration]")'),false,'Reopening cannot replay')
 for(const [metric,shape] of [['champion-kills','stars'],['baron-kills','ribbons'],['dragon-kills','sparks'],['herald-kills','tiles']]){
  await product.action('finish');await product.action('configureChallenge',{metricId:metric,target:1,rules:product.display().rules});await product.action('start')
  await screenUntil('document.querySelector("[data-testid=overlay-completed]")?.textContent==="0"')
  await product.action('completed',1);await screenUntil(`!!document.querySelector(".burst-${shape}")`)
 }
 // Test the actual CSS response to reduced motion, not just a media-query string.
 const debuggerApi=getOverlay().webContents.debugger
 debuggerApi.attach('1.3')
 try{
  await debuggerApi.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]})
  await product.action('overlayPreview');await screenUntil('!!document.querySelector("[data-testid=overlay-celebration]")')
  assert.equal(await screen('getComputedStyle(document.querySelector(".broadcast-confetti")).display'),'none')
  assert.equal(await screen('getComputedStyle(document.querySelector(".broadcast-victory")).animationName'),'none')
 }finally{await debuggerApi.sendCommand('Emulation.setEmulatedMedia',{features:[]});debuggerApi.detach()}
 await product.action('overlaySettings',{...product.display().overlaySettings,animations:false})
 await product.action('overlayPreview');await screenUntil('!document.querySelector("[data-testid=overlay-celebration]")')
 await product.action('overlaySettings',{...product.display().overlaySettings,animations:true})
 // Long names, the maximum configured values, paginated rules and a minimum window.
 const rules={likesEnabled:true,likeEvery:1000000,followEnabled:true,follow:100000,commentsEnabled:false,commentKeywords:[],gifts:Array.from({length:8},(_,i)=>({platformId:'douyin',giftId:`g${i}`,name:'非常长的礼物名称'.repeat(8),icon:'https://avatar.example.invalid/account.png',reward:100000}))}
 await product.action('rules',rules);await product.action('target',1000000);await product.action('completed',999999)
 await product.action('overlaySettings',{...product.display().overlaySettings,title:'很长的挑战标题'.repeat(15),width:300,height:420,alwaysOnTop:false})
 assert.equal(getOverlay().isAlwaysOnTop(),false)
 await screenUntil('document.querySelector("[data-testid=overlay-target]")?.textContent==="1,000,000"')
 assert.equal(await screen(fits),true,'Maximum values and long copy fit at minimum window size')
 await screenshot('overlay-boundaries.png')
 await click('[data-testid="challenge-display-settings"]')
 await until('document.querySelector(".is-embedded [data-testid=overlay-target]")?.textContent==="1,000,000"')
 assert.equal(await run('[...document.querySelectorAll(".is-embedded .broadcast-score strong")].every(n=>n.scrollWidth<=n.parentElement.clientWidth+1)'),true,'Main-window preview also fits maximum counts')
 await click('[aria-label="关闭弹窗"]')
 getOverlay().setContentSize(1600,600);await wait(200)
 assert.equal(await screen(fits),true,'Wide and short windows keep rules and scores within bounds')
 getOverlay().setContentSize(300,420);await wait(200)
 await wait(8200);assert.equal(await screen('document.querySelector(".broadcast-rules-heading").textContent.includes("2 / 4")'),true,'Rules rotate by three rows at the 420px viewport')
 await screenUntil('document.querySelector(".broadcast-rule img")?.naturalWidth>0')
 await screenshot('overlay-rules-page2.png')
 await product.action('logout');await screenUntil('!!document.querySelector(".broadcast-empty")')
 assert.equal(await screen('document.querySelectorAll(".broadcast-rule,img,[data-testid=overlay-completed]").length'),0)
 assert.equal(await screen('document.body.textContent.includes("很长的挑战标题")'),false)
 assert.equal(await screen('document.querySelectorAll(".broadcast-reason").length'),0)
 assert.deepEqual(errors,[])
 console.log('Overlay native checks passed: four themes, gift image, isolated preview, window flags, five gameplay celebrations, no replay, reduced motion, minimum size, paging, logout. Screenshots:',output)
}
