const {test}=require('node:test'),assert=require('node:assert/strict')
test('Windows installer boundary is per-user, branded, and does not delete profile data',()=>{
 const config=require('../electron-builder.cjs')
 assert.equal(config.appId,'com.playcast.desktop')
 assert.equal(config.productName,'玩播 · PlayCast')
 assert.equal(config.win.executableName,'PlayCast')
 assert.deepEqual(config.win.target,[{target:'nsis',arch:['x64']}])
 assert.equal(config.nsis.oneClick,false)
 assert.equal(config.nsis.perMachine,false)
 assert.equal(config.nsis.allowElevation,false)
 assert.equal(config.nsis.allowToChangeInstallationDirectory,true)
 assert.equal(config.nsis.deleteAppDataOnUninstall,false)
 assert.equal(config.asar,true)
 assert.equal(config.win.icon,'public/assets/brand/playcast.ico')
 assert.equal(config.nsis.installerIcon,'public/assets/brand/playcast.ico')
})
